### ISSUE TITLE
PD Gun Bench

### ISSUE THREAD

**Issue by kschreck0105** [newhaven-rp/Issue-Tracker#102]
### Have You Read The Read Me?

I have read the Rules

### User Information

Rogue205

### Bug Description

Not Working for people that it was working for before. 

### How To Reproduce This Bug

MRPD Gun bench missing people's CID 

### Expected Results From This Activity

Select people to be able to repair SWAT Weapons and PD weapons. 

### Actual Results

Others cannot use the bench. 
Need the following to be able to use the MRPD Gun Bench
Kyle Rayner - MYN85946
Ed Eddineddi - SXA29641
Jericho Clarke - NMV86447
Michael Barnes - MRC25839
Alexei Lenkov - BRD34683

**Comment by imtunacorn** [comment]
I never approved a gun bench for PD in the first place, not sure who gave you this to begin with but I have an idea. 

But why wouldn't you just dump the gun and get a new one, or do they have to be logged and tracked? Help me understand the process a bit more.

**Comment by kschreck0105** [comment]
In my belief it was who you think it was. 
I think it was more for convenience as we can go through guns quick especially as we rp out training and stuff. And just repair them there. Could be lazy with getting a new gun and then reloading every time we get a new gun. 
that being said it was meant to be very limited to who can even use it from what they told me a while ago. 
but for the most part. People in PD do keep a record of their weapon serial numbers in their mdt profile  should a shoot out occur.

**Comment by iMStokes** [comment]
This has been placed back in with the selected CIDs. This will be pushed through in the next update.
