### ISSUE TITLE
Bug Report - Fishing Rep

### ISSUE THREAD

**Issue by BLUEx154** [newhaven-rp/Issue-Tracker#104]
### Have You Read The Read Me?

I have read the Rules

### User Information

Brendan Webster aka BLUEx#5849

### Bug Description

There is an error when you do /fishrep

### How To Reproduce This Bug

/fishrep

### Expected Results From This Activity

To show fishing rep for fishing pole crafting

### Actual Results

An Error

### Screenshots/Videos

![CXJqBx8NBY](https://user-images.githubusercontent.com/99003078/211666708-be244d3f-ba69-40ee-b74b-5434e60e0d81.png)

**Comment by iMStokes** [comment]
This will be fixed in the next pushed update scheduled for tonight.
