### ISSUE TITLE
Bug Report - 

### ISSUE THREAD

**Issue by hellonurse215** [newhaven-rp/Issue-Tracker#108]
### Have You Read The Read Me?

I have read the Rules

### User Information

HelloNurse215

### Bug Description

1- Top Self Bud weights 5.5lbs 

### How To Reproduce This Bug

Give yourself or pick up 1- Top Self Bud 

### Expected Results From This Activity

Shit weighs A LOT 

### Actual Results

1- Top Self Bud weights 5.5lbs 

### Screenshots/Videos

https://cdn.discordapp.com/attachments/1061810474510983178/1061810873292816464/FiveM_b2699_GTAProcess_vjf8GDi8GL.png

**Comment by iMStokes** [comment]
This has been changed and will be in the next update push.
