### ISSUE TITLE
Server Suggestion - Add Garage to Post Ops Delivery

### ISSUE THREAD

**Issue by ccanarchy** [newhaven-rp/Issue-Tracker#110]
### Assurance

I have read the `README.md`

### Server Suggestion

Suggesting to add a garage to the delivery location similar to the one that was added to the sanitation location. 

### Reason

We can park cars if we want to do delivery runs instead of stealing cars and shooting locals
![FiveM_b2699_GTAProcess_BxyLuCddOB](https://user-images.githubusercontent.com/122235521/212501213-e831c2de-b7b6-49ed-806d-787c2177253e.png)

**Comment by iMStokes** [comment]
This has been discussed and will be implemented in an upcoming push.
