### ISSUE TITLE
Police Barricade working too well

### ISSUE THREAD

**Issue by kschreck0105** [newhaven-rp/Issue-Tracker#113]
### Have You Read The Read Me?

I have read the Rules

### User Information

Rogue205

### Bug Description

Police Barricade seems to work across multiple lanes of roadway

### How To Reproduce This Bug

Place the barricade down

### Expected Results From This Activity

block one lane of traffic

### Actual Results

blocks alot of lanes of traffic

### Screenshots/Videos

![image](https://user-images.githubusercontent.com/68434249/212574802-dd425773-0382-47f7-aeb7-4f01c30d70d0.png)

**Comment by iMStokes** [comment]
This has been addressed and will be resolved with an upcoming push.
