### ISSUE TITLE
Players with Tow Job can unimpound vehicles

### ISSUE THREAD

**Issue by kschreck0105** [newhaven-rp/Issue-Tracker#114]
### Have You Read The Read Me?

I have read the Rules

### User Information

Rogue205

### Bug Description

Not necessarily a bug, but can we change were players with the tow job to not be able to Unimpound cars from the impound lot

### How To Reproduce This Bug

get tow job and go to impound lot and unimpound a car. 

### Expected Results From This Activity

Only Police to be able to unimpound

### Actual Results

Police and Tow drivers can unimpound cars.

**Comment by iMStokes** [comment]
This has been removed for an upcoming update.
