### ISSUE TITLE
Bug Report - Midnight Chop

### ISSUE THREAD

**Issue by claymstehling** [newhaven-rp/Issue-Tracker#115]
### Have You Read The Read Me?

I have read the Rules

### User Information

Clay

### Bug Description

Midnight Chop duplicating cars. If you get a email and the accept contract, and then accept it again it will dupe the cars in different spots 

### How To Reproduce This Bug

Get chop email -> Accept email -> Chop Car -> Accept same email again -> Go to new spot -> Same car -> Insta have keys -> No need to lockpick car 

### Expected Results From This Activity

Not to be able to double accept email

### Actual Results

Sometimes you can double accept emails

### Screenshots/Videos

![image (21)](https://user-images.githubusercontent.com/85035402/212749386-e42b0979-3027-43f4-826e-1cb77bece647.png)
![image (22)](https://user-images.githubusercontent.com/85035402/212749388-6828466f-7ed1-4b57-a482-b9bcb1c18a7c.png)

![image (23)](https://user-images.githubusercontent.com/85035402/212749438-cb77b40b-3a8e-4225-a386-4b39ff19dd70.png)
![image (24)](https://user-images.githubusercontent.com/85035402/212749445-1c501278-f526-4d34-b767-f618b36b0efc.png)
![image (25)](https://user-images.githubusercontent.com/85035402/212749451-31ecdaef-361b-4124-a8f2-27cc1c08aeb4.png)
![image (26)](https://user-images.githubusercontent.com/85035402/212749454-d7502052-4305-4e91-aef4-13ec82227030.png)

**Comment by iMStokes** [comment]
This Issue has been addressed and has been fixed for the next update push.
