### ISSUE TITLE
ATM at White Snake

### ISSUE THREAD

**Issue by FiliusRP** [newhaven-rp/Issue-Tracker#116]
### Assurance

I have read the `README.md`

### Server Suggestion

Need an ATM at White Snake Mech Shop

### Reason

The closest ATM is a distance down the road  and now that one cannot pull money from the shop account at the computer in the shop, we need it to get money to pay for mats and for customers to get cash, etc

**Comment by imtunacorn** [comment]
I have added an ATM to the front of the building. It is currently live. :)
