### ISSUE TITLE
Bug Report - 

### ISSUE THREAD

**Issue by akwarlock92** [newhaven-rp/Issue-Tracker#118]
### Have You Read The Read Me?

I have read the Rules

### User Information

akwarlock

### Bug Description

Invisable wall on carson ave. hit twice myself and had a cadet hit it as well

### How To Reproduce This Bug

drive down carson road going south west

### Expected Results From This Activity

unsure

### Actual Results

hiting something unknown and getting launched in the air or just plain stopped

### Screenshots/Videos

https://medal.tv/games/gta-v/clips/QYFfEPDrrLrS9/d1337HQ7Rhfh?invite=cr-MSx4S1YsNzAyODU0OTYs

**Comment by imtunacorn** [comment]
After extensive testing and trying to recreate the invisible collision, it has been determined that you are experiencing a desync problem. It would appear that there was a light pole that had fallen, and it desync from Infinity One-Sync **visually**, but the collision remained. 

Sorry you had to experience that though, the video was kinda funny but really shitty at the same time.
