### ISSUE TITLE
Bug Report - Fishing Tournament Timer Inconsistent 

### ISSUE THREAD

**Issue by ccanarchy** [newhaven-rp/Issue-Tracker#130]
### Have You Read The Read Me?

I have read the Rules

### User Information

Cee Jay

### Bug Description

The timer for the fishing tournaments counts down from 35 minutes but it seems the events are only 15 minutes long and they end on the 20 minute mark on the timer. clip provided and been confirmed by multiple sources to be consistent with every tournament. 

### How To Reproduce This Bug

Join a fishing tournament and wait 15 minutes

### Expected Results From This Activity

Either a 35 minute tournament or a 15 minute timer, consistency

### Actual Results

a 15 minute tournament with a 35 minute timer, inconsistency 

### Screenshots/Videos

https://medal.tv/games/gta-v/clips/RyTcQ_DufzI6U/d13376cyiIBM?invite=cr-MSxPdnAsNzk4OTAwMjcs

**Comment by iMStokes** [comment]
This has been fixed for a future update. Thank you.
