### ISSUE TITLE
Bug Report - Many Cayo Locals With Same Interaction Prompt

### ISSUE THREAD

**Issue by ccanarchy** [newhaven-rp/Issue-Tracker#131]
### Have You Read The Read Me?

I have read the Rules

### User Information

Cee Jay

### Bug Description

Many locals on Cayo Perico will offer to "Order supplies" for what seems to be a drug process but when interacting with them nothing happens. 

### How To Reproduce This Bug

Go to Cayo Perico and attempt to be social near the docks 

### Expected Results From This Activity

Most locals will not interact but few possibly will. There was not a set expectation in mind so I cannot say for certain what the proper expected outcome would have been. 

### Actual Results

Many locals interact with the same prompt that does not seem to do anything. 

### Screenshots/Videos

https://medal.tv/games/gta-v/clips/RxPUh2f6cSWtW/d1337e1VdR72?invite=cr-MSw1ZzYsNzk4OTAwMjcs
https://medal.tv/games/gta-v/clips/RxQ9dt7RhNcAj/d1337Cu6Lw7s?invite=cr-MSxxaDQsNzk4OTAwMjcs

**Comment by iMStokes** [comment]
This has been handled for the next update. Thank you.
