### ISSUE TITLE
Bug Report - Boat Cruise Control Broken

### ISSUE THREAD

**Issue by ccanarchy** [newhaven-rp/Issue-Tracker#132]
### Have You Read The Read Me?

I have read the Rules

### User Information

Cee Jay

### Bug Description

The cruise control feature does not currently seem to work for boats although it used to before one of the recently updates. 

### How To Reproduce This Bug

Try to use the cruise control while in a boat while accelerating or coasting

### Expected Results From This Activity

The cruise control should keep the boat at a steady speed unless hit by a large wave or the player accelerates/decelerates 

### Actual Results

"cruise control unavailable" 

### Screenshots/Videos

https://medal.tv/games/gta-v/clips/RzU7KGyYXFCnM/d1337nAf1Mvh?invite=cr-MSxDelMsNzk4OTAwMjcs

**Comment by iMStokes** [comment]
This has been fixed for a future update.
