### ISSUE TITLE
Pd Not getting bobcat dispatch

### ISSUE THREAD

**Issue by kschreck0105** [newhaven-rp/Issue-Tracker#135]
### Have You Read The Read Me?

I have read the Rules

### User Information

Rogue205

### Bug Description

Bobcat was robbed, no PD dispatch to it

### How To Reproduce This Bug

I suppose rob bobcat and see...

### Expected Results From This Activity

someone robs it and PD gets a dispatch

### Actual Results

PD didnt get a dispatch from one that happened about 9:00 PM CST

**Comment by iMStokes** [comment]
This will be fixed in the next update (should be pushed this evening.)
