### ISSUE TITLE
Bug Report - Issues with deep sea fishing. 

### ISSUE THREAD

**Issue by hellonurse215** [newhaven-rp/Issue-Tracker#137]
### Have You Read The Read Me?

I have read the Rules

### User Information

HelloNurse215

### Bug Description

While deep sea fishing and using a lure and fishing bait, fishing will be cancelled when a wave hits the boat. 

### How To Reproduce This Bug

Fish in deep sea spots. 

### Expected Results From This Activity

Assumed reason for issue: When a wave hits the boat it cancels out the fishing emote when you stumble causing you to lose the bait and not catch a fish. 

### Actual Results

You don't catch a fish. 

### Screenshots/Videos

https://www.twitch.tv/videos/1720031714

**Comment by TheRealMommaLIsa** [comment]
after what I thought was progress with a larger boat being better.  I went and bought the 80k boat at the marina and it seems to be as bad as the dingy you can rent.  I waste more bait that I catch fish.

**Comment by TheRealMommaLIsa** [comment]
I rented the longfin for 5k and was able to fish pretty succesfully,  only a couple of hiccups.....

**Comment by Skreeeeee** [comment]
IME I have not had issues with the Shitzu as long as I stay in the main seating area and don't go up onto the hull. Even the swim platform is pretty solid though I have had it canceled there once.

**Comment by TheRealMommaLIsa** [comment]
I have been doing some science,  if you don't use the anchor you can catch all the fish as long as you don't float too far out,  also know that it affects the females more than the males....

**Comment by iMStokes** [comment]
Threw in some fixes for this - and with some testing with female peds - it seems this problem has been fixed and will be loaded into the next set of updates.
