### ISSUE TITLE
Bug Report - kicked for duplicating while working at burgershot

### ISSUE THREAD

**Issue by Niysiah** [newhaven-rp/Issue-Tracker#138]
### Have You Read The Read Me?

I have read the Rules

### User Information

Ash Vercetti

### Bug Description

Was making heartstoppers at burgershot and got kicked for duplicating them after 6

### How To Reproduce This Bug

I'm not sure you can.. I made 6 heart stoppers and it kicked me. not sure because i've made a lot in a row before and not had this issue.

### Expected Results From This Activity

to make many heartstoppers to sell

### Actual Results

getting kicked for duplicating

**Comment by iMStokes** [comment]
This has been fixed with the most recent push coming in. If there are any further issues, please let me know.
