### ISSUE TITLE
Server Suggestion - Previously Removed Emotes + Broken Prop Emotes

### ISSUE THREAD

**Issue by opeperoni** [newhaven-rp/Issue-Tracker#140]
### Assurance

I have read the `README.md`

### Server Suggestion

1. There are certain emotes of the sunbathing variety that were previously removed because they could be used in unrealistic ways. Those are currently available after the latest emote update.

2. There are several prop emotes, that if you select them through the emote menu, it breaks the emote menu and you must take a nap to get the emote menu back.
- BS Bleeder (/e bleeder)
- Bong 2 (/e bong2)
- BS Coke (/e bscoke)
- BS Cheese Wrap (/e cheesewrap)
- BS Doubleshot (/e doubleshot)
- Probably all BS items. I stopped testing.
- Strawberry Ice Cream (/e icecreams)
- Vanilla Ice Cream (/e icecreamv)
- Grapefruit Juice (/e juiceg)
- Possibly other Juices: Lemon, Orange, Raspberry (didn't test)
- Chocolate Milkshake (/e milkshakec)
- Probably all other milkshakes and cups
- Papers (/e papers)
- Pineapple (/e pineapple)
- Present (/e present)
- Toolbox 3 (/e toolbox3)
- Toolbox 4 (/e toolbox4)
- Torpedo (/e torpedo)
- Vape 2 (/e vape2)

### Reason

1. Make it make sense

2. Stops Emote Menu from breaking.

**Comment by iMStokes** [comment]
These have  already been addressed and will be pushed in the next update.
