### ISSUE TITLE
Old AOD Stress Zone

### ISSUE THREAD

**Issue by claymstehling** [newhaven-rp/Issue-Tracker#148]
### Have You Read The Read Me?

I have read the Rules

### User Information

Clay

### Bug Description

The stress zone that was at the old AOD compound is still there 

### How To Reproduce This Bug

Go to the location and stand there for a bit

### Expected Results From This Activity

You shouldn't get stressed

### Actual Results

You do get stressed 

### Screenshots/Videos

![20230203100517_1](https://user-images.githubusercontent.com/85035402/216650688-a85311e2-23ec-424a-b56f-318209786beb.jpg)
![20230203100551_1](https://user-images.githubusercontent.com/85035402/216650692-d9a10b30-036e-4910-ae88-2d2bea5d5bb1.jpg)

**Comment by iMStokes** [comment]
This will be removed in the upcoming update!
