### ISSUE TITLE
Old Mirrors Stress Relief Zone

### ISSUE THREAD

**Issue by claymstehling** [newhaven-rp/Issue-Tracker#149]
### Have You Read The Read Me?

I have read the Rules

### User Information

Clay

### Bug Description

The old mirrors stress relief zone is still there despite the MLO being gone

### How To Reproduce This Bug

Go to the old mirrors spot and wait

### Expected Results From This Activity

You don't get destressed

### Actual Results

You are getting destressed

### Screenshots/Videos

![20230203100918_1](https://user-images.githubusercontent.com/85035402/216651786-b601bd15-c93d-4514-8d2a-a988fcb45572.jpg)

**Comment by iMStokes** [comment]
This will be removed in the upcoming update!
