### ISSUE TITLE
Bug Report - Map Bug at POP's Diner

### ISSUE THREAD

**Issue by BLUEx154** [newhaven-rp/Issue-Tracker#151]
### Have You Read The Read Me?

I have read the Rules

### User Information

Emily Battle aka BLUEx#5849

### Bug Description

ATM Facing the wrong way at POP's Diner.

### How To Reproduce This Bug

Go to POP's Diner

### Expected Results From This Activity

The ATM will be facing the correct way.

### Actual Results

The ATM is facing the wrong way.

### Screenshots/Videos

https://i.imgur.com/rCvFRfL.jpeg https://i.imgur.com/yC6zlTz.jpeg

**Comment by iMStokes** [comment]
This will be resolved with an upcoming update. Thank you. :)
