### ISSUE TITLE
Bug Report - Business App Hire/Fire

### ISSUE THREAD

**Issue by shelbs341** [newhaven-rp/Issue-Tracker#153]
### Have You Read The Read Me?

I have read the Rules

### User Information

sheLBY

### Bug Description

In the business app for Redline, the managers can hire and fire people. 

### How To Reproduce This Bug

Set job to manager (level 3)

### Expected Results From This Activity

This should be an owner only function.

### Actual Results

Managers can hire and fire people, but for Redline we'd like to make it an owner role only function.

**Comment by 0xSavageD** [comment]
Fixed in 714668e3f46cd7ff1a1c37330faa46e2b052b2ee

**Comment by 0xSavageD** [comment]
Fixed in 714668e3f46cd7ff1a1c37330faa46e2b052b2ee

**Comment by iMStokes** [comment]
This will be resolved in an upcoming update in the next day or so.
