### ISSUE TITLE
Bug Report - Limey's Bugs

### ISSUE THREAD

**Issue by exclusivegirl** [newhaven-rp/Issue-Tracker#162]
### Have You Read The Read Me?

I have read the Rules

### User Information

E.G. (exclusivegirl)

### Bug Description

Issues reported by Limey's Owner Elle Miller | LexiePNG#3200: 

- Chocolate Ice Cream in the ingredients is the wrong one. The one in the supplies is the actual product rather than the tub ingredient. It should be the one in the tub like the other ones I pictured.

- Peanut Butter is still scuffed as well, I think it's just something wrong with the ingredient as having it in my pockets breaks my pockets. I can make the peanut butter bowl still, but my pockets are scuffed after doing so and I have to take a nap.

- There is no business bank account so I'm not sure where the money goes when I charge people unless I manually make one (Which I assume isn't intentional)

- Grade 0 which is now "juicer" for me doesn't work, when I try to give someone that rank from the boss menu, it ended up giving him assistant manager. From my phone, nothing happens. Every other rank works but the lowest one. (Unless this rank only works when hiring someone but I haven't been able to try that, either way I cannot demote someone to it)

- Smoothies not being hydrating but we already touched on that

### How To Reproduce This Bug

N/A

### Expected Results From This Activity

N/A

### Actual Results

N/A

### Screenshots/Videos

![image](https://user-images.githubusercontent.com/86116245/217171677-0f66669a-302c-425d-9cf9-4e2def23805d.png)

**Comment by iMStokes** [comment]
These all have been addressed and fixed for the most recent patch, minus the level 0 employment job. This is across the board for all jobs, and will be looked into. :)
