### ISSUE TITLE
Bug Report - Lockpicks breaking 

### ISSUE THREAD

**Issue by DK-22GZ** [newhaven-rp/Issue-Tracker#177]
### Have You Read The Read Me?

I have read the Rules

### User Information

DK

### Bug Description

When hotwiring a vehicle with brand new Advanced lock pick it just breaks once you get keys. 

### How To Reproduce This Bug

Just by using the advanced lock pick 

### Expected Results From This Activity

keep the lock pick and get keys to vehicle 

### Actual Results

losing the lock pick after one use and having to buy another one 

### Screenshots/Videos

https://medal.tv/games/gta-v/clips/ULHogm25rshOx/d1337ecCNmdZ?invite=cr-MSxJMk8sMjIxNTQ0MzAs

https://medal.tv/games/gta-v/clips/ULg1ct-z1nvY1/d1337JWvtFr6?invite=cr-MSxBRWYsMjIxNTQ0MzAs

**Comment by iMStokes** [comment]
This has been addressed and fixed for an upcoming patch.
