### ISSUE TITLE
Kicked while looking in dope bag

### ISSUE THREAD

**Issue by TheJayNation** [newhaven-rp/Issue-Tracker#38]
A player reported they were kicked from the server after looking into their dope bag. 
This is the first report I have seen for this so am unsure that others are having this issue.

![Git Hub Dope Kick](https://user-images.githubusercontent.com/97364159/192658183-7e88a510-7d64-474e-b222-06133b7542f1.png)
![Pockets for dope scuff](https://user-images.githubusercontent.com/97364159/192658219-30437076-a186-43cb-9f11-ea924eb1eb13.png)

**Comment by baritonebear** [comment]
Haven't seen another report and unable to replicate issue. Likely just a happenstance connection issue.
