### ISSUE TITLE
Bank Truck Location Not Updating  

### ISSUE THREAD

**Issue by Lisssssaa** [newhaven-rp/Issue-Tracker#50]
![Screenshot (658)](https://user-images.githubusercontent.com/115129065/194206196-2dc6fdfb-fa49-4fda-a2ba-d029f2ad61e5.png)

https://medal.tv/games/gta-v/clips/DBgkYEc5SrefS/d13373p4jY86?invite=cr-MSxWenEsNTIyOTYwNjAs

**Comment by baritonebear** [comment]
Fixed with update to kevin-banktrucks and qbcore
