### ISSUE TITLE
Paleto Bank Started with 3 PD on duty but unable to complete.

### ISSUE THREAD

**Issue by kschreck0105** [newhaven-rp/Issue-Tracker#52]
Paleto Bank being robbed, 3 officers on duty when it was tried. Dapper, Mike and IV all streaming it. 
it was started but they Couldn't complete the heist. 

Text: From Development Ticket 0472

Just wanna ask if this is working as it is supposed to
U can hit the first hack to paleto with less than 4 cops on 
Cops get alerted
They get there
And then u can’t do the last hack
We did one last night cops got alerted , showed up then we couldn’t do last hack

**Comment by baritonebear** [comment]
qb SHA-135942285a4aa3decf6e817214f5f90feae88e7b add cop check to first hack
