### ISSUE TITLE
Floating building parts

### ISSUE THREAD

**Issue by KrigTroff** [newhaven-rp/Issue-Tracker#54]
Heya. I just died randomly at the Towing Depot. Not sure how it happened exactly, but I got into the truck and locked the vehicle as to be in my head for a min - I was thrown into different camera views several times injuring me each time til it eventually killed me.  There is some floating structures remaining here from the Previous Vapid building that may have something to do with it, other than that, dunno. 

That's the floating structures from the old building I mentioned.
![floating stuff](https://user-images.githubusercontent.com/81516249/196051305-caf17afb-7c6a-430e-909b-4976c7c101cc.jpeg)

**Comment by iMStokes** [comment]
This has been resolved previously!
