### ISSUE TITLE
QB-ambulance Armory isn't using job level perms

### ISSUE THREAD

**Issue by baritonebear** [newhaven-rp/Issue-Tracker#61]
Everything is available to all job levels. Made sure all job levels are accurate based on the attached spreadsheet.

https://docs.google.com/spreadsheets/d/1kPM_l_BXOn5_pe1458uMi9DVZwYzUmsaoppqqihHJZ8/edit?usp=sharing

**Comment by 0xSavageD** [comment]
Fixed in : QB - 72af4d5fbb68aa943102f5812aad78a5d104e7d3
