### ISSUE TITLE
Food/weed delivery and house robbery polyzones overlapping

### ISSUE THREAD

**Issue by esrivs** [newhaven-rp/Issue-Tracker#79]
While some houses do allow you to rob or deliver food to them simultaneously without issue, some polyzones seem to be overlapping such as the one at the location pictured

![image 2](https://user-images.githubusercontent.com/120232075/208471056-71116dec-c86e-43e1-be18-2be8a3ca06c2.jpg)
![image](https://user-images.githubusercontent.com/120232075/208470420-ad5fa564-9617-468f-bfdc-2dc2abae5978.jpg)

**Comment by iMStokes** [comment]
This will be resolved with the upcoming patch.
