### ISSUE TITLE
Character slot issue

### ISSUE THREAD

**Issue by esrivs** [newhaven-rp/Issue-Tracker#84]
Players are unable to purchase more than 1 additional (4th) character slot through the airport store.  (If this was intended, cool, but if not this may need to be advertised differently in the kiosk menu at the airport desk)

A small number of players have expressed a desire in purchasing more than 1 additional slot - it is advertised that players can possess up to 7 character slots but the airport desk doesn't allow them to complete the transaction

**Comment by iMStokes** [comment]
This will be resolved with the upcoming patch.
