### ISSUE TITLE
Several Crucial Discord Logs are not working 

### ISSUE THREAD

**Issue by esrivs** [newhaven-rp/Issue-Tracker#85]
### MAIN DISCORD
**Not working:**
- ALL channels in the "Staff Logs" category
- ALL channels in the "General Logs" category

### LOG DISCORD
**Issues:**
-  **join-leave does not include player IDs when people connect/disconnect!!!!!!**
- bans (in staff category, not pac) doesn't always seem to be 100% reliable
- **death logs!!!**

**Not working:**
- /me logs
-  staff-vehicle-commands
- motels
- bobcat robbery
- okok-purchases 
- store-robbery

**Comment by baritonebear** [comment]
The logs from the main discord were only there in case any got forgotten on their transfer to the logs discord. I'll remove these channels.

When patch is pushed:
Join-leave now includes IDs
Death Logs will work (non-weapon deaths may show as "unknown" while we work out the kinks, but at least they'll show)
/me logs fixed
Bobcat fixed
store robbery fixed

Others still to do.

**Comment by imtunacorn** [comment]
Casino logs also not working properly.
