### ISSUE TITLE
Bug Report - Pineapple Juice

### ISSUE THREAD

**Issue by Tyzareal** [newhaven-rp/Issue-Tracker#90]
### Have You Read The Read Me?

I have read the Rules

### User Information

Ty'zareal

### Bug Description

Pineapple isn't giving hydration status anymore, just relaxation. Cranberry juice works fine but no longer Pineapple juice

### How To Reproduce This Bug

Just drink it

### Expected Results From This Activity

increased hydration

### Actual Results

Feeling more relaxed

**Comment by ccanarchy** [comment]
Adding to this post, the "Tits or Tots" from VU have the same result, no hunger but you get relaxed

**Comment by iMStokes** [comment]
> Pineapple isn't giving hydration status anymore, just relaxation. Cranberry juice works fine but no longer Pineapple juice

This issue has been resolved, and will be implemented in the next update.

**Comment by iMStokes** [comment]
This will be fixed with the upcoming push.
