### ISSUE TITLE
Housing Stash Not Accessible 

### ISSUE THREAD

**Issue by ccanarchy** [newhaven-rp/Issue-Tracker#91]
### Have You Read The Read Me?

I have read the Rules

### User Information

Cee Jay

### Bug Description

In my house/property I am able to open the locker stashes but not the inventory that I set through the housing menu. I have tried replacing it and reloggging and still cannot access it. 

### How To Reproduce This Bug

Own a property and place an inventory 

### Expected Results From This Activity

Stash should open as usual and like the other locker storages in the room

### Actual Results

Nothing happens

### Screenshots/Videos

![FiveM_b2699_GTAProcess_VoBWShuyg3](https://user-images.githubusercontent.com/122235521/211220952-80468df0-ec0a-48c8-aad9-a70c60b3eb6a.jpg)

**Comment by iMStokes** [comment]
I believe this will be due to a potential issue in regards to items recently removed from the inventory. They will be placed back in tonight to check if this will fix the issue for the stashes.
