### ISSUE TITLE
Bulletproof tires are still in mechanic crafting

### ISSUE THREAD

**Issue by ccanarchy** [newhaven-rp/Issue-Tracker#92]
### Assurance

I have read the `README.md`

### Vehicle Issues

Mechanics are still able to make bulletproof tires even though we are not supposed to make/sell them. It is in the performance parts section.

### Screenshot or Video

![FiveM_b2699_GTAProcess_KyyJfBGUbC](https://user-images.githubusercontent.com/122235521/211222419-7f006c36-c7b5-43b4-a134-c7f896d334df.png)

**Comment by iMStokes** [comment]
![image](https://user-images.githubusercontent.com/52089484/211223562-ba827d52-3874-4523-a244-fba3fdc139c6.png)

This has been removed for the next update push.
