### ISSUE TITLE
Bug Report - Advanced repair kits are not in the craftable menu for boosted 

### ISSUE THREAD

**Issue by ThaHoppah** [newhaven-rp/Issue-Tracker#93]
### Have You Read The Read Me?

I have read the Rules

### User Information

Roscoe

### Bug Description

The menu has no option for the advanced repair kit to be crafted in any of the channels

### How To Reproduce This Bug

.

### Expected Results From This Activity

To be able to make the repair kit

### Actual Results

cant

**Comment by iMStokes** [comment]
![image](https://user-images.githubusercontent.com/52089484/211223464-2908a0ac-8702-4aa4-a8b6-dab354ee5fb1.png)

This has been fixed for the next update push.

**Comment by ThaHoppah** [comment]
wicked thanks
