### ISSUE TITLE
Seat Belt not working

### ISSUE THREAD

**Issue by kschreck0105** [newhaven-rp/Issue-Tracker#94]
### Have You Read The Read Me?

I have read the Rules

### User Information

Rogue205

### Bug Description

Seatbelt is showing being buckled but you can still get out

### How To Reproduce This Bug

get in car. put seatbelt on. try and get out of car. Boom

### Expected Results From This Activity

i put seatbelt on and i would like to stay in car. 

### Actual Results

i can get out and i ejecto easier.

**Comment by iMStokes** [comment]
This has been fixed for the next update push. :)
