### ISSUE TITLE
MRPD Parking Garage

### ISSUE THREAD

**Issue by kschreck0105** [newhaven-rp/Issue-Tracker#95]
### Have You Read The Read Me?

I have read the Rules

### User Information

Rogue205

### Bug Description

garage lableled mrpdpublic Is no longer there

### How To Reproduce This Bug

walk to the front of MRPD and its not there. 

There is the parking lot but its not named MRPD Public. Its names Mrpd

### Expected Results From This Activity

would like to pull my car out of there

### Actual Results

cant open it at all

### Screenshots/Videos

![image](https://user-images.githubusercontent.com/68434249/211229682-1163d5cb-6014-415c-9f5d-036804949afb.png)

**Comment by kschreck0105** [comment]
And when you pull a car our of the garage. is puts you here
![image](https://user-images.githubusercontent.com/68434249/211229738-67b171a4-409d-4c5f-9525-4a894020486d.png)

**Comment by kschreck0105** [comment]
![image](https://user-images.githubusercontent.com/68434249/211230918-fb96560a-c8b6-425d-baec-ba07e264b17f.png)
in this pic you can see the blip arrow thing for it way below the map

**Comment by iMStokes** [comment]
This should be resolved with the next upcoming push. Please feel free to report back with any issues following that, or let us know if you're good to close.
