### ISSUE TITLE
Bug Report - 

### ISSUE THREAD

**Issue by BasedWiggles54** [newhaven-rp/Issue-Tracker#97]
### Have You Read The Read Me?

I have read the Rules

### User Information

Phil Block

### Bug Description

The Games at Insert Coin: Seems like the money not going to the work account and its seems that you can play the game with no money in your pocket pretty sure it not pulling from your bank when you have no cash. could we raise the game fee to 50-100 even? and we wasnt fully sure if we have the hardest hacker game the one at the bank job (they was asking about one with 4 squares?) 

### How To Reproduce This Bug

just playing and testing the games and bank accounts 

### Expected Results From This Activity

realtime update on the money 

### Actual Results

money going being took but not sure where its going

**Comment by iMStokes** [comment]
Company account issues have been fixed.
Continued money issues will be fixed in an upcoming push.
