### ISSUE TITLE
Bug Report - Solo Chop double job

### ISSUE THREAD

**Issue by theMagnificentJay** [newhaven-rp/Issue-Tracker#99]
### Have You Read The Read Me?

I have read the Rules

### User Information

Jhwk#0666

### Bug Description

When accepting solo chop job and clicking accept (double clicked out of habit) received two locations for pickup.

### How To Reproduce This Bug

Possible to reproduce by accepting job pickup request via phone email and spamming the accept button. Although this is not tested on my part.

### Expected Results From This Activity

Receive one location for job.

### Actual Results

Received multiple (2) locations for active job.

### Screenshots/Videos

![image](https://user-images.githubusercontent.com/70526834/211291005-10d3d328-6aa2-4fdd-a915-591401622ad2.png)
![image](https://user-images.githubusercontent.com/70526834/211291082-ab159358-e967-4c1d-b559-1e58f2ba7eeb.png)
![image](https://user-images.githubusercontent.com/70526834/211291095-592ae700-868d-4d54-a69f-244ddf0c76d3.png)

**Comment by iMStokes** [comment]
This Issue has been addressed and has been fixed for the next update push.
